spring.datasource.url=jdbc:postgresql://localhost:5432/acao_atleta
spring.datasource.username=postgres
spring.datasource.password=aluno
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/Projeto-integrador/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true