spring.datasource.name=acao_atleta
spring.datasource.url=jdbc:postgresql://dpg-d8k110pkh4rs73elboh0-a.oregon-postgres.render.com:5432/acao_atleta
spring.datasource.username=acao_atleta_user
spring.datasource.password=Cd6n0tvkuywv40dVBX23jTH32LklsZMM
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/Projeto-integrador/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true